### ISSUE TITLE
Add folia support

### ISSUE THREAD

**Issue by Toyo-tez** [Jckf/DH-Support#44]

**Comment by Jckf** [comment]
Have you tested the plugin as-is with Folia? How does it behave?

**Comment by Toyo-tez** [comment]
I will get home and compile it with folia-supported flag

**Comment by Jckf** [comment]
Decided to test this myself and had a go at making it work. Have a look at #46 :)

**Comment by Toyo-tez** [comment]
Thank you for testing and adding support! My GPU died so i could not test (my CPU does not have igpu :c) but thank you su much! I will try it on muy server once i fix muy fualty GPU BIOS
