### ISSUE TITLE
Versions

### ISSUE THREAD

**Issue by EdoEquin0x** [Jckf/DH-Support#47]
May I ask for a broader spectrum of support MC version ? Like 1.20.1-1.20.2-1.20.4 and 1.21 ? 1.21 only is a bit restrictive

**Comment by Jckf** [comment]
Yes, I've been thinking about how to do this, but I'm not sure how :thinking: Suggestions welcome!

**Comment by EdoEquin0x** [comment]
I have no idea to be honest... Only thing I know is that on forge and fabric not much change between 1.20.1, 1.20.2 and 1.20.4, maybe it's the same for spigot/paper, or maybe you could try to transform your concept into a server-sided mod instead of a plugin ?

**Comment by Jckf** [comment]
Server-side DH already works on both the client and on the server, so if you run a Fabric server you should use that instead :) This project specifically exists for people that want a plugin.

Anyway, I made something that seems to work for building multiple versions at once. Guess I should try to match the versions DH supports.

**Comment by EdoEquin0x** [comment]
I run a forge server. I did not knew that server-sided LOD updates worked when the mod is installed on the server tho
