### ISSUE TITLE
Mod

### ISSUE THREAD

**Issue by furax124** [Jckf/DH-Support#58]
Make a mod version? For forge fabric server or hybrid

**Comment by TicTecOfficial** [comment]
dhsupport is plugin only. you'll need a nightly build of distant horizons serverside branch to put in your forge/fabric folder

**Comment by TicTecOfficial** [comment]
you need the plugin installed on the server and the mod installed on the client simultaneously in order for them to work.

**Comment by Jckf** [comment]
TicTec is correct. DH with server capabilities is originally a mod. The plugin is the alternative. Use the server-side fork if you have the option :) Link to the Discord thread with download links in the readme.
